CREATE TABLE IF NOT EXISTS address(
	address_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    street_1 VARCHAR(50) NOT NULL,
    street_2 VARCHAR(50) NOT NULL DEFAULT '',
	city VARCHAR(20) NOT NULL,
    state VARCHAR(2) NOT NULL,
    zip VARCHAR(5) NOT NULL,
    last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_update_by VARCHAR(25)
    );