CREATE TABLE IF NOT EXISTS employee_info(
	employee_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    person_id BIGINT NOT NULL UNIQUE,
    FOREIGN KEY(person_id) REFERENCES person(person_id),

    rate DECIMAL(2,2) NOT NULL DEFAULT 0,

    last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_update_by VARCHAR(25)
    );